name: worly_auth
description: Worly ITP107 Finals laboratory - Login, Sign-Up, and Home using named routes.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/mascot_signup_exact.png
    - assets/images/mascot_login_exact.png
    - assets/images/auth_background.png
    - assets/images/mascot_home_ai.png
